version: '3.1'

services:
  mysite:
    container_name: mysite
    image: ruby:2.6.9
    volumes:
      - ./:/app
    working_dir: /app
    user: ${CURRENT_UID}
    environment:
      HOME: /app
  web:
    container_name: mysite-web
    image: nginx
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 5555:80
    environment:
      NGINX_DISABLE_SYMLINKS: false
